// Auto-generated by BAC Unified
// Problem: ∫(x² + 2x)dx from 0 to 2

use noon::prelude::*;

fn scene(win_rect: Rect) -> Scene {
    let mut scene = Scene::new(win_rect);

    // Background
    let bg = scene.rectangle()
        .with_size(20.0, 15.0)
        .with_color(Color::rgb(0.1, 0.1, 0.15))
        .make();
    scene.play(bg.fade_in()).run_time(0.5);

    // Coordinate Axes
    let x_axis = scene.line()
        .from(-6, 0.0)
        .to(6, 0.0)
        .with_color(Color::WHITE)
        .make();
    
    let y_axis = scene.line()
        .from(0.0, -6)
        .to(0.0, 6)
        .with_color(Color::WHITE)
        .make();
    
    scene.play(x_axis.show_creation()).run_time(1.0);
    scene.play(y_axis.show_creation()).run_time(1.0);
    // Function points
    let mut prev_point = None;

    for i in 0..100 {
        let x = -5.0 + (i as f32 / 100.0 * 10.0);
        let y = 1*x*x + 2*x + 0;

        let point = scene.dot()
            .with_position(x, y)
            .with_color(Color::CYAN)
            .make();
        
        if let Some(prev) = prev_point {
            let line = scene.line()
                .from_point(prev)
                .to_point(point)
                .with_color(Color::CYAN)
                .make();
            scene.play(line.show_creation()).run_time(0.02);
        }
        prev_point = Some(point);
    }

    // Shade area from x=0 to x=2
    for i in 0..=50 {
        let x = 0 + (i as f32 / 50.0) * (2 - 0);
        let y = 1*x*x + 2*x + 0;
        
        let point = scene.dot()
            .with_position(x, y)
            .with_color(Color::CYAN.with_alpha(0.3))
            .make();
        scene.play(point.fade_in()).run_time(0.05);
    }

    let text_861 = scene.text("∫ = 20/3")
        .with_position(-3.0, -4.0)
        .with_color(Color::RED)
        .with_font_size(48.0)
        .make();
    scene.play(text_861.show_creation()).run_time(1.0);

    scene
}

fn main() {
    noon::app(model).update(update).view(view).run();
}

fn model<'a>(app: &App) -> Scene {
    app.new_window()
        .size(1920, 1080)
        .title("BAC Unified - ∫(x² + 2x)dx from 0 to 2")
        .view(view)
        .build()
        .unwrap();
    scene(app.window_rect())
}

fn update(app: &App, scene: &mut Scene, _update: Update) {
    scene.update(app.time, app.window_rect());
}

fn view(app: &App, scene: &Scene, frame: Frame) {
    let draw = app.draw();
    draw.background().color(Color::rgb(0.1, 0.1, 0.15));
    scene.draw(draw.clone());
    draw.to_frame(app, &frame).unwrap();
}
