"""
BAC Unified - AI to Noon Code Generator (Extended)
Supports Math, Physics, and Chemistry visualizations
"""

import json
import re
from typing import List, Dict, Any


class NoonCodeGenerator:
    """Generates Noon (Rust) animation code from AI solutions."""

    def __init__(self):
        self.template_start = """// Auto-generated by BAC Unified
// Problem: {problem}
// Type: {problem_type}

use noon::prelude::*;

fn scene(win_rect: Rect) -> Scene {{
    let mut scene = Scene::new(win_rect);

    // Background
    let bg = scene.rectangle()
        .with_size(20.0, 15.0)
        .with_color(Color::rgb(0.1, 0.1, 0.15))
        .make();
    scene.play(bg.fade_in()).run_time(0.5);
"""
        self.template_end = """
    scene
}}

fn main() {{
    noon::app(model).update(update).view(view).run();
}}

fn model<'a>(app: &App) -> Scene {{
    app.new_window()
        .size(1920, 1080)
        .title("BAC Unified - {title}")
        .view(view)
        .build()
        .unwrap();
    scene(app.window_rect())
}}

fn update(app: &App, scene: &mut Scene, _update: Update) {{
    scene.update(app.time, app.window_rect());
}}

fn view(app: &App, scene: &Scene, frame: Frame) {{
    let draw = app.draw();
    draw.background().color(Color::rgb(0.1, 0.1, 0.15));
    scene.draw(draw.clone());
    draw.to_frame(app, &frame).unwrap();
}}
"""

    def generate_axes(self, x_range=(-5, 5), y_range=(-5, 5)):
        x_min, x_max = x_range
        y_min, y_max = y_range
        return f"""
    // Coordinate Axes
    let x_axis = scene.line()
        .from({x_min - 1}, 0.0)
        .to({x_max + 1}, 0.0)
        .with_color(Color::WHITE)
        .make();
    
    let y_axis = scene.line()
        .from(0.0, {y_min - 1})
        .to(0.0, {y_max + 1})
        .with_color(Color::WHITE)
        .make();
    
    scene.play(x_axis.show_creation()).run_time(1.0);
    scene.play(y_axis.show_creation()).run_time(1.0);
"""

    def generate_text(self, text, position, color="Color::GREEN", size=32.0):
        x, y = position
        safe_text = text.replace('"', '\\"')
        return f'''
    let text_{abs(hash(text)) % 10000} = scene.text("{safe_text}")
        .with_position({x}, {y})
        .with_color({color})
        .with_font_size({size})
        .make();
    scene.play(text_{abs(hash(text)) % 10000}.show_creation()).run_time(1.0);
'''

    # ==================== MATH ====================

    def generate_math_integral(self, problem, solution):
        code = self.generate_axes()

        # Extract bounds
        bounds_match = re.search(r"from\s+(\d+)\s+to\s+(\d+)", problem)
        x_start, x_end = (
            (0, 2)
            if not bounds_match
            else (int(bounds_match.group(1)), int(bounds_match.group(2)))
        )

        # Plot function (example: x^2 + 2x)
        code += """
    // Plot function f(x) = x² + 2x
    let mut prev_point = None;
    for i in 0..100 {
        let x = -5.0 + (i as f32 / 100.0 * 10.0);
        let y = x*x + 2.0*x;
        
        let point = scene.dot()
            .with_position(x, y)
            .with_color(Color::CYAN)
            .make();
        
        if let Some(prev) = prev_point {
            let line = scene.line()
                .from_point(prev)
                .to_point(point)
                .with_color(Color::CYAN)
                .make();
            scene.play(line.show_creation()).run_time(0.02);
        }
        prev_point = Some(point);
    }
"""
        # Shade area
        code += f"""
    // Shade area under curve
    for i in 0..=50 {{
        let x = {x_start} + (i as f32 / 50.0) * ({x_end} - {x_start});
        let y = x*x + 2.0*x;
        
        let point = scene.dot()
            .with_position(x, y)
            .with_color(Color::CYAN.with_alpha(0.3))
            .make();
        scene.play(point.fade_in()).run_time(0.05);
    }}
"""
        # Show answer
        answer = solution.get("answer", "20/3")
        code += self.generate_text(
            f"Answer: {answer}", (-3.0, -4.0), "Color::RED", 48.0
        )

        return code

    def generate_math_derivative(self, problem, solution):
        code = self.generate_axes()

        # Plot derivative
        code += """
    // Plot f(x) and f'(x)
    let mut prev_f = None;
    let mut prev_df = None;
    
    for i in 0..100 {
        let x = -5.0 + (i as f32 / 100.0 * 10.0);
        let y = x*x + 2.0*x;      // f(x)
        let dy = 2.0*x + 2.0;      // f'(x)
        
        // f(x) in cyan
        let point_f = scene.dot()
            .with_position(x, y)
            .with_color(Color::CYAN)
            .make();
        
        // f'(x) in red
        let point_df = scene.dot()
            .with_position(x, dy)
            .with_color(Color::RED)
            .make();
    }
"""
        # Show derivative formula
        code += self.generate_text("f'(x) = 2x + 2", (-4.0, 4.0), "Color::YELLOW", 36.0)

        return code

    # ==================== PHYSICS ====================

    def generate_physics_projectile(self, problem, solution):
        code = """
    // Ground
    let ground = scene.rectangle()
        .with_size(20.0, 0.5)
        .with_position(0.0, -5.0)
        .with_color(Color::rgb(0.3, 0.5, 0.2))
        .make();
    scene.play(ground.fade_in()).run_time(0.5);
"""
        # Extract parameters
        v0 = solution.get("v0", 30)
        angle = solution.get("angle", 45)

        code += self.generate_text(
            f"v₀ = {v0} m/s, θ = {angle}°", (-5.0, 5.0), "Color::WHITE", 24.0
        )

        # Animate projectile
        code += f"""
    // Projectile animation
    let mut ball = scene.circle()
        .with_radius(0.3)
        .with_position(-7.0, -4.0)
        .with_color(Color::RED)
        .make();
    
    scene.play(ball.show_creation()).run_time(0.5);
    
    let v0 = {v0}.0;
    let angle = {angle}.0;
    let g = 9.8;
    let mut prev_pos = (-7.0, -4.0);
    let dt = 0.05;
    let mut t = 0.0;
    
    while t < 3.0 {{
        let x = -7.0 + v0 * angle.to_radians().cos() * t;
        let y = -4.0 + v0 * angle.to_radians().sin() * t - 0.5 * g * t * t;
        
        if y < -4.75 {{ break; }}
        
        scene.play(ball.move_to(x, y)).run_time(dt);
        prev_pos = (x, y);
        t += dt;
    }}
"""
        # Show range
        range_val = (
            v0**2 * 2 * (angle * 3.14159 / 180).sin() * (angle * 3.14159 / 180).cos()
        ) / 9.8
        code += self.generate_text(
            f"Range: {range_val:.1f}m", (3.0, 3.0), "Color::YELLOW", 32.0
        )

        return code

    def generate_physics_circuit(self, problem, solution):
        code = """
    // Battery
    let battery = scene.rectangle()
        .with_size(0.5, 2.0)
        .with_position(-6.0, 0.0)
        .with_color(Color::GRAY)
        .make();
    scene.play(battery.show_creation()).run_time(0.5);
"""
        # Resistor
        code += """
    let resistor = scene.rectangle()
        .with_size(2.0, 0.5)
        .with_position(-1.0, 2.5)
        .with_color(Color::BROWN)
        .make();
    scene.play(resistor.show_creation()).run_time(0.5);
"""
        # Capacitor
        code += """
    let cap_top = scene.rectangle()
        .with_size(0.2, 1.0)
        .with_position(0.0, 1.5)
        .with_color(Color::BLUE)
        .make();
    let cap_bottom = scene.rectangle()
        .with_size(0.2, 1.0)
        .with_position(0.0, -0.5)
        .with_color(Color::BLUE)
        .make();
    scene.play(cap_top.show_creation()).run_time(0.5);
    scene.play(cap_bottom.show_creation()).run_time(0.5);
"""
        # Equations
        code += self.generate_text("V = IR", (3.0, 4.0), "Color::WHITE", 28.0)
        code += self.generate_text("τ = RC", (3.0, 3.0), "Color::WHITE", 28.0)

        return code

    # ==================== CHEMISTRY ====================

    def generate_chemistry_molecule(self, problem, solution):
        formula = solution.get("formula", "C₂H₆O")

        code = self.generate_text(
            f"Molecule: {formula}", (-3.0, 6.0), "Color::YELLOW", 40.0
        )

        # Draw atoms
        code += """
    // Carbon atoms
    let c1 = scene.circle()
        .with_radius(0.4)
        .with_position(-3.0, 0.0)
        .with_color(Color::GRAY)
        .make();
    
    let c2 = scene.circle()
        .with_radius(0.4)
        .with_position(-1.0, 0.0)
        .with_color(Color::GRAY)
        .make();
    
    // C-C bond
    let cc_bond = scene.line()
        .from(-2.6, 0.0)
        .to(-1.4, 0.0)
        .with_color(Color::WHITE)
        .with_thickness(4.0)
        .make();
    
    scene.play(c1.show_creation()).run_time(0.5);
    scene.play(c2.show_creation()).run_time(0.5);
    scene.play(cc_bond.show_creation()).run_time(0.5);
    
    // Hydrogen atoms
    let h1 = scene.circle()
        .with_radius(0.25)
        .with_position(-3.5, 0.8)
        .with_color(Color::WHITE)
        .make();
    
    let h2 = scene.circle()
        .with_radius(0.25)
        .with_position(-3.5, -0.8)
        .with_color(Color::WHITE)
        .make();
    
    scene.play(h1.show_creation()).run_time(0.3);
    scene.play(h2.show_creation()).run_time(0.3);
    
    // Oxygen
    let oxygen = scene.circle()
        .with_radius(0.35)
        .with_position(1.0, 0.0)
        .with_color(Color::RED)
        .make();
    
    // O-H bond
    let oh_bond = scene.line()
        .from(0.65, 0.0)
        .to(1.0, -0.35)
        .with_color(Color::WHITE)
        .with_thickness(3.0)
        .make();
    
    scene.play(oxygen.show_creation()).run_time(0.5);
    scene.play(oh_bond.show_creation()).run_time(0.3);
"""
        # Properties
        molar_mass = solution.get("molar_mass", "46.07 g/mol")
        code += self.generate_text(
            f"Molar Mass: {molar_mass}", (3.0, 4.0), "Color::CYAN", 24.0
        )

        return code

    def generate_chemistry_reaction(self, problem, solution):
        equation = solution.get("equation", "A + B → C")

        code = self.generate_text(
            "Chemical Reaction:", (-5.0, 5.0), "Color::ORANGE", 32.0
        )
        code += self.generate_text(equation, (-5.0, 3.5), "Color::WHITE", 28.0)

        return code

    # ==================== MAIN ====================

    def generate_from_solution(self, problem: str, solution: Dict) -> str:
        """Main method: Generate complete Noon code from solution."""

        # Detect problem type
        problem_lower = problem.lower()

        if any(
            kw in problem_lower for kw in ["intégral", "∫", "integral", "primitive"]
        ):
            problem_type = "Math - Integral"
            code = self.generate_math_integral(problem, solution)
        elif any(kw in problem_lower for kw in ["dérivé", "derivative"]):
            problem_type = "Math - Derivative"
            code = self.generate_math_derivative(problem, solution)
        elif any(kw in problem_lower for kw in ["projectile", "lancer", "trajectory"]):
            problem_type = "Physics - Projectile Motion"
            code = self.generate_physics_projectile(problem, solution)
        elif any(kw in problem_lower for kw in ["circuit", "résistance", "capacitor"]):
            problem_type = "Physics - Electric Circuit"
            code = self.generate_physics_circuit(problem, solution)
        elif any(kw in problem_lower for kw in ["molécule", "molecule", "atome"]):
            problem_type = "Chemistry - Molecule"
            code = self.generate_chemistry_molecule(problem, solution)
        elif any(kw in problem_lower for kw in ["réaction", "reaction"]):
            problem_type = "Chemistry - Reaction"
            code = self.generate_chemistry_reaction(problem, solution)
        else:
            problem_type = "General"
            code = self.generate_text(problem, (-4.0, 4.0))

        # Build final code
        full_code = self.template_start.format(
            problem=problem.replace('"', '\\"'), problem_type=problem_type
        )
        full_code += code
        full_code += self.template_end.format(title=problem[:30])

        return full_code


if __name__ == "__main__":
    generator = NoonCodeGenerator()

    # Test with different problem types
    test_cases = [
        {
            "problem": "∫(x² + 2x)dx from 0 to 2",
            "solution": {"answer": "20/3", "type": "integral"},
        },
        {
            "problem": "Calculate derivative of f(x) = x² + 2x",
            "solution": {"derivative": "2x + 2", "type": "derivative"},
        },
        {
            "problem": "Projectile motion: v0=30m/s, angle=45°",
            "solution": {"v0": 30, "angle": 45, "type": "projectile"},
        },
        {
            "problem": "RC Circuit with R=10Ω, C=100μF",
            "solution": {"R": 10, "C": 100e-6, "type": "circuit"},
        },
        {
            "problem": "Ethanol molecule structure",
            "solution": {
                "formula": "C₂H₅OH",
                "molar_mass": "46.07 g/mol",
                "type": "molecule",
            },
        },
        {
            "problem": "Combustion of ethanol",
            "solution": {"equation": "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O", "type": "reaction"},
        },
    ]

    for i, test in enumerate(test_cases):
        code = generator.generate_from_solution(test["problem"], test["solution"])

        filename = f"generated_{test['solution']['type']}_{i + 1}.rs"
        with open(filename, "w") as f:
            f.write(code)

        print(f"✓ Generated: {filename} ({test['problem'][:40]}...)")

    print("\nAll examples generated!")
